-- SWAS Triage Batch Update v3
-- Source: Kruidvat, ICI PARIS XL, medeco.com, level.co, controlid.com.br, adamsrite.com, remaining_assets (ASSA ABLOY)
-- Generated 2026-08-03
-- NOTE: Whatnot, REI, Mars, Lyst reports excluded - no finding IDs present in source text.
-- NOTE: ID 22834 excluded - conflicting definitions across two source docs (GraphQL introspection
--       on yaleconnecthub.com vs origin-IP-bypass on controlid.com.br). Verify manually which is correct.

BEGIN;

CREATE TEMP TABLE _triage_batch3 (
    finding_id  INTEGER PRIMARY KEY,
    new_status  TEXT NOT NULL,
    outcome     TEXT,
    reason      TEXT NOT NULL
);

INSERT INTO _triage_batch3 (finding_id, new_status, outcome, reason) VALUES
(21811,'dismissed','informative','logic_hunter hypothesis chained on disproven CORS premise; tool own follow-up failed to confirm (WAF blocked/404/no evidence)'),
(21842,'dismissed','informative','logic_hunter hypothesis chained on disproven CORS premise; tool own follow-up failed to confirm (WAF blocked/404/no evidence)'),
(21843,'dismissed','informative','logic_hunter hypothesis chained on disproven CORS premise; tool own follow-up failed to confirm (WAF blocked/404/no evidence)'),
(21844,'dismissed','informative','logic_hunter hypothesis chained on disproven CORS premise; tool own follow-up failed to confirm (WAF blocked/404/no evidence)'),
(21860,'dismissed','informative','logic_hunter hypothesis chained on disproven CORS premise; tool own follow-up failed to confirm (WAF blocked/404/no evidence)'),
(21876,'dismissed','informative','logic_hunter hypothesis chained on disproven CORS premise; tool own follow-up failed to confirm (WAF blocked/404/no evidence)'),
(21878,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21880,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21881,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21882,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21883,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21884,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21885,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21886,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21888,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21889,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21890,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21891,'dismissed','informative','CORS suffix bypass: every request hit Akamai WAF block page (AkamaiGHost), real backend/app CORS logic never reached'),
(21892,'dismissed','informative','logic_hunter hypothesis chained on disproven CORS premise; tool own follow-up failed to confirm (WAF blocked/404/no evidence)'),
(21893,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass confirmed real but no additional impact demonstrated; program excludes rate-limit/WAF-bypass-only findings without further impact'),
(21894,'dismissed','informative','backup_temp_file_disclosure false positive: live public Publitas viewer page, not a leaked backup'),
(21910,'dismissed','informative','logic_hunter CORS hypothesis self-refuted (404/403/inconclusive on all probes)'),
(21912,'dismissed','out_of_scope','CORS suffix bypass tested: Akamai WAF blocks non-browser, edge rewrites ACAO for browsers, only public catalog data exposed; program excludes CORS on non-sensitive endpoints'),
(21919,'dismissed','out_of_scope','CORS suffix bypass tested: Akamai WAF blocks non-browser, edge rewrites ACAO for browsers, only public catalog data exposed; program excludes CORS on non-sensitive endpoints'),
(21925,'dismissed','out_of_scope','CORS suffix bypass tested: Akamai WAF blocks non-browser, edge rewrites ACAO for browsers, only public catalog data exposed; program excludes CORS on non-sensitive endpoints'),
(21926,'dismissed','informative','logic_hunter CORS hypothesis self-refuted (404/403/inconclusive on all probes)'),
(21927,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21928,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21929,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21930,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21931,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21932,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21933,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21934,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21935,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21936,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21937,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21938,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21939,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21940,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21941,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21942,'dismissed','informative','logic_hunter CORS hypothesis self-refuted (404/403/inconclusive on all probes)'),
(21943,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21944,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21945,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21946,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21947,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21948,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21949,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21950,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21951,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21952,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21953,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21954,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21955,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21956,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21958,'dismissed','informative','logic_hunter CORS hypothesis self-refuted (404/403/inconclusive on all probes)'),
(21959,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21960,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21961,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21962,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21963,'dismissed','informative','logic_hunter CORS hypothesis self-refuted (404/403/inconclusive on all probes)'),
(21964,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(21965,'dismissed','out_of_scope','cewe.kruidvat.be origin IP bypass - third-party CEWE infra, not AS Watson-controlled'),
(21966,'dismissed','out_of_scope','CORS suffix bypass on public static/media endpoint, same non-exploitable pattern as tested api.kruidvat.be sample; program excludes CORS on non-sensitive endpoints'),
(22779,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22780,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22781,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22782,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22783,'dismissed','informative','leaked_source_map: Bootstrap public source map, API_KEY is placeholder not real credential'),
(22784,'reviewed',NULL,'CSRF PoC confirmed on registration form (no token, no Origin validation) but low impact - registration only, not authenticated action; needs manual check whether it causes victim account-linkage before submitting'),
(22785,'reviewed',NULL,'CSRF PoC confirmed on registration form (no token, no Origin validation) but low impact - registration only, not authenticated action; needs manual check whether it causes victim account-linkage before submitting'),
(22786,'dismissed','informative','logic_hunter hypothesis speculative/untestable, no supporting evidence, built on non-submittable origin IP finding'),
(22787,'dismissed','informative','logic_hunter hypothesis speculative/untestable, no supporting evidence, built on non-submittable origin IP finding'),
(22788,'dismissed','informative','logic_hunter hypothesis speculative/untestable, no supporting evidence, built on non-submittable origin IP finding'),
(22789,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22790,'dismissed','informative','leaked_source_map: Bootstrap public source map, API_KEY is placeholder not real credential'),
(22791,'dismissed','informative','logic_hunter hypothesis speculative/untestable, no supporting evidence, built on non-submittable origin IP finding'),
(22792,'reviewed',NULL,'unauthenticated GraphQL __typename mutation succeeds but is cosmetic only; logic_hunter enumerated schema and found no sensitive mutations (no updateEmail/updatePassword/deleteAccount); insufficient impact to submit standalone'),
(22793,'dismissed','out_of_scope','sqlmap against Apple/Google Play listing URL - third-party infra, not ASSA ABLOY asset'),
(22794,'dismissed','out_of_scope','sqlmap against Apple/Google Play listing URL - third-party infra, not ASSA ABLOY asset'),
(22795,'dismissed','informative','graphql_introspection_exposed: standard Adobe AEM/Magento 714-type schema fingerprint, informational only'),
(22796,'reviewed',NULL,'unauthenticated GraphQL __typename mutation succeeds but is cosmetic only; logic_hunter enumerated schema and found no sensitive mutations (no updateEmail/updatePassword/deleteAccount); insufficient impact to submit standalone'),
(22797,'dismissed','informative','logic_hunter IDOR/broken-access hypotheses, all require authenticated cross-account session to test, unverifiable by agentic tool, no high-privilege mutations in schema'),
(22798,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22799,'dismissed','out_of_scope','sqlmap against Apple/Google Play listing URL - third-party infra, not ASSA ABLOY asset'),
(22800,'dismissed','informative','logic_hunter IDOR/broken-access hypotheses, all require authenticated cross-account session to test, unverifiable by agentic tool, no high-privilege mutations in schema'),
(22801,'dismissed','informative','graphql_introspection_exposed: standard Adobe AEM/Magento 714-type schema fingerprint, informational only'),
(22802,'dismissed','informative','logic_hunter IDOR/broken-access hypotheses, all require authenticated cross-account session to test, unverifiable by agentic tool, no high-privilege mutations in schema'),
(22803,'dismissed','informative','graphql_introspection_exposed: standard Adobe AEM/Magento 714-type schema fingerprint, informational only'),
(22804,'dismissed','out_of_scope','sqlmap against Apple/Google Play listing URL - third-party infra, not ASSA ABLOY asset'),
(22805,'dismissed','informative','logic_hunter IDOR/broken-access hypotheses, all require authenticated cross-account session to test, unverifiable by agentic tool, no high-privilege mutations in schema'),
(22806,'reviewed',NULL,'host_header_injection on content.adamsrite.com - cache poisoning already refuted by logic_hunter (no-cache headers), password reset poisoning refuted (no redirect on GET/HEAD); low value AEM content server, verify Location header reflection before submitting'),
(22807,'dismissed','informative','logic_hunter hypothesis refuted (cache poisoning impossible, GET-batching impossible, no sensitive mutations, unverifiable without authenticated session)'),
(22808,'dismissed','informative','nuclei tasmota-config-webui false-fired against Apple App Store listing URL, not a Level server'),
(22809,'dismissed','informative','nuclei tasmota-config-webui false-fired against Apple App Store listing URL, not a Level server'),
(22810,'reviewed',NULL,'unauthenticated GraphQL __typename mutation succeeds but is cosmetic only; logic_hunter enumerated schema and found no sensitive mutations (no updateEmail/updatePassword/deleteAccount); insufficient impact to submit standalone'),
(22811,'dismissed','informative','logic_hunter hypothesis refuted (cache poisoning impossible, GET-batching impossible, no sensitive mutations, unverifiable without authenticated session)'),
(22812,'dismissed','informative','graphql_introspection_exposed: standard Adobe AEM/Magento 714-type schema fingerprint, informational only'),
(22813,'reviewed',NULL,'unauthenticated GraphQL __typename mutation succeeds but is cosmetic only; logic_hunter enumerated schema and found no sensitive mutations (no updateEmail/updatePassword/deleteAccount); insufficient impact to submit standalone'),
(22814,'dismissed','informative','logic_hunter hypothesis refuted (cache poisoning impossible, GET-batching impossible, no sensitive mutations, unverifiable without authenticated session)'),
(22815,'dismissed','out_of_scope','sqlmap against Google Play Store listing URL - third-party infra, not ASSA ABLOY asset'),
(22816,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22817,'dismissed','informative','logic_hunter hypothesis refuted (cache poisoning impossible, GET-batching impossible, no sensitive mutations, unverifiable without authenticated session)'),
(22818,'dismissed','informative','graphql_introspection_exposed: standard Adobe AEM/Magento 714-type schema fingerprint, informational only'),
(22819,'dismissed','informative','graphql_introspection_exposed: standard Adobe AEM/Magento 714-type schema fingerprint, informational only'),
(22820,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: no associated exploitable vulnerability, explicitly excluded by program policy'),
(22821,'reviewed',NULL,'host_header_injection on content.adamsrite.com - cache poisoning already refuted by logic_hunter (no-cache headers), password reset poisoning refuted (no redirect on GET/HEAD); low value AEM content server, verify Location header reflection before submitting'),
(22822,'dismissed','informative','logic_hunter hypothesis refuted (cache poisoning impossible, GET-batching impossible, no sensitive mutations, unverifiable without authenticated session)'),
(22823,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: no associated exploitable vulnerability, explicitly excluded by program policy'),
(22824,'dismissed','informative','leaked_source_map: Bootstrap public source map, API_KEY is placeholder not real credential'),
(22825,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: no associated exploitable vulnerability, explicitly excluded by program policy'),
(22826,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: no associated exploitable vulnerability, explicitly excluded by program policy'),
(22827,'dismissed','informative','leaked_source_map: Bootstrap public source map, API_KEY is placeholder not real credential'),
(22828,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: no associated exploitable vulnerability, explicitly excluded by program policy'),
(22829,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: no associated exploitable vulnerability, explicitly excluded by program policy'),
(22830,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: no associated exploitable vulnerability, explicitly excluded by program policy'),
(22831,'dismissed','informative','graphql_introspection_exposed: standard Adobe AEM/Magento 714-type schema fingerprint, informational only'),
(22832,'dismissed','informative','logic_hunter hypothesis untestable/premise invalid (0 steps taken / built on false-positive leaked key)'),
(22833,'dismissed','informative','logic_hunter hypothesis untestable/premise invalid (0 steps taken / built on false-positive leaked key)'),
(22835,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22836,'dismissed','informative','graphql_introspection_exposed: standard Adobe AEM/Magento 714-type schema fingerprint, informational only'),
(22837,'dismissed','informative','exposed_admin_panel false positive: Tray e-commerce 404 page contains word "dashboard" in template, no real admin interface, refuted by logic_hunter'),
(22838,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22839,'dismissed','informative','graphql_introspection_exposed: standard Adobe AEM/Magento 714-type schema fingerprint, informational only'),
(22840,'dismissed','informative','node-express-dev-env: tech fingerprint only, default Express error pages, no debug endpoints or sensitive data exposed'),
(22841,'dismissed','informative','node-express-dev-env: tech fingerprint only, default Express error pages, no debug endpoints or sensitive data exposed'),
(22842,'dismissed','duplicate','duplicate of submitted pprof/metrics finding 22844, same exposed debug surface'),
(22843,'dismissed','duplicate','duplicate of submitted pprof/metrics finding 22844, same exposed debug surface'),
(22844,'submitted','accepted','CVE-2019-11248 unauthenticated go-pprof debug endpoint, confirmed manually - private repo paths, OAuth2 middleware, Kafka topology disclosed'),
(22845,'dismissed','informative','exposed prometheus/actuator metrics endpoint, informational only per program policy, no associated exploitable vuln'),
(22846,'dismissed','informative','exposed prometheus/actuator metrics endpoint, informational only per program policy, no associated exploitable vuln'),
(22847,'dismissed','informative','sqlmap against actual idsecure.com.br asset but result is unverified/unknown severity, no confirmed injection'),
(22848,'reviewed',NULL,'host_header_injection on webflow.controlid.com.br - tool claims Location header reflects injected Host; needs manual curl verification before submitting, check password-reset/email flow impact if confirmed'),
(22849,'dismissed','informative','node-express-dev-env: tech fingerprint only, default Express error pages, no debug endpoints or sensitive data exposed'),
(22850,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: no associated exploitable vulnerability, explicitly excluded by program policy'),
(22851,'reviewed',NULL,'CVE-2025-59474 possible Jenkins /securityRealm/signup anonymous self-registration on in-scope subdomain builds.fw.level.co - needs manual verification before submitting'),
(22852,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22853,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: no associated exploitable vulnerability, explicitly excluded by program policy'),
(22854,'dismissed','informative','logic_hunter hypothesis refuted by agentic investigation (all common dev/API paths returned 404, premise invalid)'),
(22855,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22856,'dismissed','out_of_scope','sqlmap against Apple/Google Play listing URL - third-party infra, not ASSA ABLOY asset'),
(22857,'dismissed','informative','logic_hunter hypothesis refuted by agentic investigation (all common dev/API paths returned 404, premise invalid)'),
(22858,'dismissed','informative','exposed_admin_panel false positive: Tray e-commerce 404 page contains word "dashboard" in template, no real admin interface, refuted by logic_hunter'),
(22859,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22860,'dismissed','informative','node-express-dev-env: tech fingerprint only, default Express error pages, no debug endpoints or sensitive data exposed'),
(22861,'dismissed','informative','logic_hunter hypothesis refuted by agentic investigation (all common dev/API paths returned 404, premise invalid)'),
(22862,'dismissed','informative','logic_hunter hypothesis refuted by agentic investigation (all common dev/API paths returned 404, premise invalid)'),
(22863,'dismissed','informative','node-express-dev-env: tech fingerprint only, default Express error pages, no debug endpoints or sensitive data exposed'),
(22864,'reviewed',NULL,'host_header_injection on webflow.controlid.com.br - tool claims Location header reflects injected Host; needs manual curl verification before submitting, check password-reset/email flow impact if confirmed'),
(22865,'dismissed','informative','node-express-dev-env: tech fingerprint only, default Express error pages, no debug endpoints or sensitive data exposed'),
(22866,'dismissed','out_of_scope','origin_ip_waf_cdn_bypass: program excludes HTTP headers without associated exploitable vulnerability'),
(22867,'dismissed','informative','logic_hunter hypothesis refuted by agentic investigation (all common dev/API paths returned 404, premise invalid)')
ON CONFLICT (finding_id) DO NOTHING;

UPDATE findings f
SET status = t.new_status,
    likely_program_outcome = t.outcome,
    triage_reasoning = t.reason
FROM _triage_batch3 t
WHERE f.id = t.finding_id;

-- Sanity check before commit
SELECT new_status, outcome, count(*)
FROM _triage_batch3
GROUP BY new_status, outcome
ORDER BY 1,2;

COMMIT;
