"""
detective.py package - "detective mindset" checks: pure-Python, zero-new-binary
vulnerability detectors that don't need a CLI tool (unlike tools.py, which
shells out to subfinder/nuclei/etc.).

This used to be a single ~8,900 line detective.py file. It is now split by
vulnerability category into submodules for maintainability:
  - shared.py         shared helpers/constants (logger, timeout, hostname/URL
                       validation, entropy calc, secret-scan regexes)
  - injection.py       SQLi, SSTI, XXE, LDAP/XPath injection, command injection,
                       prototype pollution, NoSQL injection, LFI/traversal, etc.
  - ssrf.py            reflected/blind SSRF, cloud metadata credential theft
  - auth_access.py     JWT, CORS, CSRF, IDOR, verb tampering, mass assignment,
                       session/cookie handling, admin panel access, API keys
  - cloud_storage.py   S3/Azure bucket and Firebase exposure
  - client_side.py     XSS variants, clickjacking, insecure upload
  - infra_exposure.py  leaked config/CI files, debug endpoints, exposed DB/dev
                       tool admin consoles, backup/dump files, missing headers
  - recon_misc.py      subdomain takeover, cache deception/poisoning, WAF
                       fingerprinting, GraphQL introspection, open redirect,
                       websocket downgrade/CSWSH, weak TLS, business-logic recon

Every function is read-only / non-destructive - no writes, no exploitation,
just detection. Each returns None when nothing is found, or a dict describing
the finding when something is. Callers (pipeline.py) decide what to do with
that.

Every top-level name (public AND private/underscore-prefixed) is re-exported
explicitly here - not via `from .x import *`, which silently drops
underscore-prefixed names by Python convention and broke git_dumper.py
(_HARDCODED_SECRET_PATTERNS) and pipeline.py (_looks_like_sane_url,
_SENSITIVE_FILE_HINTS) on first deploy of this split. Explicit imports below
are equivalent to the original flat detective.py module namespace.
"""

from .shared import (
    logger,
    _TIMEOUT,
    _MAX_REASONABLE_URL_LENGTH,
    _extract_hostname,
    _looks_like_sane_url,
    _SENSITIVE_FILE_HINTS,
    _TOKEN_PATTERN,
    _TEST_FIXTURE_PATH_HINTS,
    _PLACEHOLDER_VALUE_HINTS,
    _WAF_CHALLENGE_PATH_HINTS,
    _INHERENTLY_PUBLIC_PATH_HINTS,
    _shannon_entropy,
    _replace_query_param,
)

from .injection import (
    _SQLI_DELAY_SECONDS,
    _SQLI_TIMING_PAYLOADS,
    _SQLI_CONTROL_PAYLOAD,
    _MAX_PARAMS_PER_URL,
    check_blind_sqli_timing,
    _CRLF_MARKER,
    _CRLF_PAYLOAD,
    _inject_raw_query_param,
    _evaluate_crlf_response,
    check_crlf_injection,
    _LOGIN_CANDIDATE_PATHS,
    _LOGIN_FIELD_COMBOS,
    _check_login_bypass,
    check_blind_nosql_injection,
    _TYPE_CONFUSION_VARIANTS,
    check_json_type_confusion,
    check_http_param_pollution,
    check_host_header_injection,
    _ssti_probes,
    check_ssti,
    check_prototype_pollution,
    _SQLI_ERROR_SIGNATURES,
    _SQLI_ERROR_PROBES,
    check_sqli_error_based,
    _XXE_PAYLOAD,
    _XXE_ERROR_SIGNATURES,
    check_xxe_error_based,
    _DESERIALIZATION_SIGNATURES,
    check_insecure_deserialization_signature,
    _PATH_TRAVERSAL_PROBES,
    _PATH_TRAVERSAL_SIGNATURES,
    check_path_traversal_lfi,
    _CMDI_DELAY_SECONDS,
    _CMDI_PAYLOAD_TEMPLATES,
    _CMDI_CONTROL_TEMPLATE,
    check_os_command_injection,
    _PHP_WRAPPER_PROBES,
    _PHP_SOURCE_MARKERS,
    check_lfi_via_php_wrapper,
    _LDAP_INJECTION_PROBES,
    _LDAP_ERROR_SIGNATURES,
    check_ldap_injection_error_based,
    _XPATH_INJECTION_PROBES,
    _XPATH_ERROR_SIGNATURES,
    check_xpath_injection_error_based,
    _SQLI_BOOLEAN_TRUE,
    _SQLI_BOOLEAN_FALSE,
    check_sql_injection_boolean_based,
    _SQLI_UNION_VERSION_MARKER,
    _SQLI_UNION_TEMPLATES,
    check_sqli_union_data_extraction,
    check_lfi_arbitrary_file_confirmation,
)

from .ssrf import (
    _SSRF_PARAM_NAMES,
    _SSRF_INTERNAL_PROBES,
    check_ssrf_reflected,
    check_ssrf_blind_oob,
    _SSRF_INTERNAL_PORT_PROBES,
    _SSRF_SERVICE_BANNERS,
    check_ssrf_internal_port_scan,
    check_ssrf_gcp_metadata,
    check_ssrf_azure_metadata,
    check_ssrf_digitalocean_metadata,
    _SSRF_IAM_ROLE_LIST_PROBES,
    _AWS_CRED_JSON_KEYS,
    check_ssrf_metadata_credential_extraction,
)

from .auth_access import (
    check_cors_misconfig,
    _JWT_RE,
    check_jwt_alg_confusion,
    _API_KEY_SIGNATURES,
    check_api_key_leak_signature,
    _SEQUENTIAL_ID_RE,
    check_idor_candidate,
    _METHOD_OVERRIDE_HEADER_SETS,
    _MIN_BYPASS_BODY_LENGTH,
    check_auth_bypass_via_method_override,
    _JWT_WEAK_SECRETS,
    _JWT_HMAC_ALGS,
    check_jwt_weak_secret,
    _ADMIN_PANEL_PATHS,
    _LOGIN_FORM_INDICATORS,
    check_exposed_admin_panel,
    _MASS_ASSIGNMENT_PAYLOAD,
    check_mass_assignment_privilege_escalation,
    _VERB_TAMPERING_METHODS,
    check_auth_bypass_via_verb_tampering,
    check_predictable_token_pattern,
    check_cors_null_origin_bypass,
    check_jwt_kid_header_injection_candidate,
    _CSRF_TOKEN_FIELD_RE,
    _POST_FORM_RE,
    check_csrf_token_missing,
    check_cors_wildcard_with_credentials,
    _EXCESSIVE_EXPOSURE_FIELD_NAMES,
    _find_sensitive_keys,
    check_excessive_data_exposure_api,
    check_excessive_data_exposure_confirmed,
    _API_VERSION_RE,
    _DOWNGRADE_VERSIONS,
    check_api_version_downgrade_bypass,
    check_cors_subdomain_suffix_bypass,
    _SESSION_COOKIE_NAME_RE,
    check_insecure_cookie_without_samesite,
    _URL_SESSION_ID_PARAM_RE,
    check_session_id_in_url,
    _UUID_IN_URL_RE,
    check_predictable_uuid_version,
    check_oauth_missing_state_parameter,
    check_basic_auth_over_http,
    check_cookie_missing_secure_flag,
    _TRUSTED_LOOKING_IPS,
    check_ip_restriction_bypass_via_xff,
    check_referer_based_access_control_bypass,
    _URL_APIKEY_PARAM_RE,
    check_api_key_in_url_query_param,
    check_password_reset_user_enumeration_candidate,
    _IDENTITY_FIELD_RE,
    _extract_identity_fields,
    check_idor_unauthenticated_object_access,
    _ADMIN_FUNCTIONAL_MARKERS,
    check_admin_panel_no_auth_functional_access,
    _JWT_PRIVILEGE_CLAIM_ESCALATIONS,
    _b64url_json,
    check_jwt_forged_privilege_escalation,
    _XSS_COOKIE_EXFIL_MARKER,
    check_xss_cookie_exfiltration,
    _OAUTH_PATH_HINTS,
    _OAUTH_REDIRECT_PARAM_NAMES,
    _ATTACKER_OAUTH_DOMAIN,
    check_open_redirect_oauth_chain,
    _FORM_ACTION_RE,
    _FORM_INPUT_RE,
    _CSRF_POC_ORIGIN,
    check_csrf_poc_live_confirmation,
    _RATE_LIMIT_BYPASS_HEADERS,
    _RATE_LIMIT_PROBE_BURST,
    check_rate_limit_header_bypass,
)

from .cloud_storage import (
    _FIREBASE_URL_PATTERN,
    check_firebase_exposure,
    _BUCKET_REFERENCE_RE,
    _BUCKET_LISTING_SIGNATURES,
    check_cloud_storage_bucket_exposure,
    _AZURE_BLOB_REFERENCE_RE,
    check_azure_blob_public_exposure,
    _FIREBASE_PROJECT_RE,
    check_firebase_realtime_db_open_rules,
    _S3_OBJECT_KEY_RE,
    _GCS_OBJECT_NAME_RE,
    check_storage_bucket_object_extraction,
)

from .client_side import (
    check_reflected_xss,
    _DOM_XSS_SOURCES,
    _DOM_XSS_SINKS,
    check_dom_xss_sink_flagging,
    _FRAME_ANCESTORS_RE,
    check_clickjacking_missing_protection,
    _FILE_INPUT_RE,
    _ACCEPT_ATTR_RE,
    check_file_upload_form_candidate,
    check_insecure_svg_upload_flagging,
    _JSONP_PARAM_NAMES,
    check_jsonp_callback_xss,
)

from .infra_exposure import (
    _SECRET_KEYWORD_PATTERN,
    check_source_map_leak,
    _CONTAINER_API_TARGETS,
    _CONTAINER_PROBE_TIMEOUT,
    check_exposed_container_api,
    check_git_exposure,
    check_elasticsearch_exposure,
    _ACTUATOR_PATHS,
    check_actuator_exposure,
    _check_couchdb_exposure,
    _bson_int32_command,
    _mongo_op_query,
    _check_mongodb_exposure,
    check_nosql_db_exposure,
    _SWAGGER_PATHS,
    _SENSITIVE_API_PATH_HINTS,
    check_swagger_exposure,
    _HEAPDUMP_PATHS,
    _HEAPDUMP_MAX_BYTES,
    _HPROF_MAGIC,
    check_heapdump_exposure,
    _DEBUG_PATHS,
    check_debug_console_exposure,
    _ENV_FILE_SIGNATURES,
    check_env_file_exposure,
    _SENSITIVE_PARAM_NAME_RE,
    _EXTERNAL_RESOURCE_RE,
    check_referrer_policy_sensitive_leak,
    _GRAPHQL_SUGGESTION_QUERY,
    _GRAPHQL_SUGGESTION_RE,
    check_graphql_field_suggestion_leak,
    _SCRIPT_SRC_TAG_RE,
    check_missing_sri,
    _HARDCODED_SECRET_PATTERNS,
    check_hardcoded_secrets_and_internal_disclosure,
    check_missing_spf_dmarc,
    _BACKUP_FILE_SUFFIXES,
    _SOURCE_CODE_MARKERS,
    check_backup_temp_file_disclosure,
    check_exposed_prometheus_metrics,
    _DEPENDENCY_MANIFEST_PATHS,
    check_dependency_manifest_exposure,
    check_hsts_missing,
    _SWAGGER_SPEC_PATHS,
    check_swagger_path_enumeration_unauth,
    check_exposed_wsdl_soap_service,
    check_http_trace_method_enabled,
    check_exposed_docker_compose_file,
    _WP_CONFIG_BACKUP_PATHS,
    _WP_CONFIG_MARKERS,
    check_wordpress_config_backup_exposure,
    _STACK_TRACE_SIGNATURES,
    check_graphql_error_stack_trace_leak,
    _DEVOPS_PANEL_PATHS,
    check_exposed_devops_tool_panel,
    _PHPMYADMIN_PATHS,
    check_exposed_phpmyadmin,
    check_exposed_elmah_axd,
    check_exposed_trace_axd,
    _LARAVEL_DEBUG_MARKERS,
    check_laravel_debug_mode_exposure,
    _GIT_CONFIG_CREDENTIALS_RE,
    check_git_config_credentials_leak,
    _AWS_CREDENTIALS_PATHS,
    check_aws_credentials_file_exposure,
    _KUBECONFIG_PATHS,
    check_kubeconfig_exposure,
    check_exposed_nexus_artifactory,
    check_exposed_rabbitmq_management,
    check_exposed_grafana,
    check_exposed_minio_console,
    _raw_tcp_probe,
    check_exposed_redis_no_auth,
    check_exposed_memcached_no_auth,
    check_exposed_ftp_anonymous_login,
    check_exposed_couchdb_fauxton,
    check_exposed_zookeeper,
    check_exposed_solr_admin,
    check_jenkins_script_console_unauth,
    check_couchdb_all_dbs_unauth,
    check_spring_boot_env_exposure,
    _DJANGO_DEBUG_MARKERS,
    check_django_debug_mode_exposure,
    _ASPNET_DEBUG_MARKERS,
    check_aspnet_debug_mode_exposure,
    check_express_stack_trace_leak,
    check_npm_debug_log_exposure,
    check_travis_yml_exposure,
    check_circleci_config_exposure,
    _GITHUB_WORKFLOW_COMMON_NAMES,
    check_github_workflow_exposure,
    check_terraform_state_exposure,
    check_ansible_vault_exposure,
    check_helm_values_exposure,
    check_serverless_yml_exposure,
    check_exposed_docker_daemon_api,
    _build_pg_startup_packet,
    check_exposed_postgres_trust_auth,
    check_exposed_influxdb_no_auth,
    check_exposed_kibana_no_auth,
    _BACKUP_ARCHIVE_PATHS,
    _ZIP_MAGIC,
    _GZIP_MAGIC,
    check_backup_archive_exposure,
    _SQL_DUMP_PATHS,
    _SQL_DUMP_MARKERS,
    check_sql_dump_file_exposure,
    _LOG_FILE_PATHS,
    _ACCESS_LOG_LINE_RE,
    check_log_file_exposure,
    _HTPASSWD_LINE_RE,
    check_htpasswd_exposure,
    _GRAPHQL_SENSITIVE_FIELD_KEYWORDS,
    check_graphql_sensitive_field_exposure,
)

from .recon_misc import (
    _TAKEOVER_FINGERPRINTS,
    check_subdomain_takeover,
    _CACHE_DECEPTION_PATH_HINTS,
    check_cache_deception,
    check_file_entropy,
    _REDIRECT_PARAM_PATTERN,
    _OPEN_REDIRECT_PROBE,
    check_open_redirect,
    _WEAK_CSP_PATTERN,
    check_csp_weakness,
    _GRAPHQL_PATHS,
    _INTROSPECTION_QUERY,
    check_graphql_introspection,
    _WAF_SIGNATURES,
    check_waf_fingerprint,
    _WEBSOCKET_GUID,
    _WS_PROBE_PATHS,
    _CSWSH_ATTACKER_ORIGIN,
    _ws_accept_key,
    _try_ws_handshake,
    check_websocket_cswsh,
    _OPTIONSBLEED_PROBE_COUNT,
    _STANDARD_HTTP_METHODS,
    check_apache_optionsbleed,
    _OPEN_REDIRECT_ENCODED_PAYLOADS,
    _REDIRECT_PARAM_NAME_RE,
    check_open_redirect_encoding_bypass,
    _GRAPHQL_BLIND_MUTATION_PROBES,
    check_unauthenticated_graphql_mutation,
    check_negative_number_business_logic_candidate,
    check_web_cache_poisoning_unkeyed_header,
    _WS_URL_RE,
    check_websocket_downgrade,
    check_graphql_query_via_get,
    _CDN_EDGE_RANGES,
    _CDN_EDGE_NETWORKS,
    _is_known_cdn_edge_ip,
    check_origin_ip_waf_bypass,
    _META_REFRESH_PARAM_RE,
    check_open_redirect_via_meta_refresh,
    check_insecure_tls_weak_protocol,
    check_dangling_ns_delegation_takeover,
)
